### ISSUE TITLE
概览

### ISSUE THREAD

**Issue by UCloudDocs** [UCloudDoc-Team/cube#1]
# 概览

查看产品文档请点击下方链接

[https://docs.ucloud.cn/cube/README](https://docs.ucloud.cn/cube/README)

**Comment by vevlins** [comment]
两年前就推出来的产品，到现在还是要客户经理开通权限才能使用，问东问西，跟防贼一样。

**Comment by jaya-sun** [comment]
产品当前处于测试阶段，为了确保可用性和服务质量暂未对外开放，如有不便十分抱歉。后续我们也会有计划的进行部分地域开放。
